name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Linter
        run: make lint

      - name: Test
        run: make test

      - name: Integration Test
        run: make integration-test

      - name: EndToEnd test
        run: make end2end-test
