name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Code Formatting
        run: make fmtcheck

      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Integration Test
        run: make integration-test

      - name: EndToEnd test
        run: make end2end-test
